### ISSUE TITLE
Problems with installing Kopf

### ISSUE THREAD

**Issue by Yzord** [lmenezes/elasticsearch-kopf#279] opened 2015-05-26 12:45 UTC
I have some troubles with my indexes, so i wanted to install Kopf. So i downloaded the zip file from GIT and placed it on the server. Next thing i do is:

[root@havok elasticsearch]# bin/plugin -install lmenezes/elasticsearch-kopf -u file:///root/elasticsearch-kopf-master.zip
-> Installing lmenezes/elasticsearch-kopf...
Trying file:/root/elasticsearch-kopf-master.zip...
Downloading ....................DONE
Installed lmenezes/elasticsearch-kopf into /usr/share/elasticsearch/plugins/kopf
Identified as a _site plugin, moving to _site structure ...
[root@havok elasticsearch]#

It has installed it in /usr/share/elasticsearch/plugins/kopf and it has included a _site folder.

But when i go to http://localhost:9200/_plugin/kopf really nothing is happening (404). Also replaced localhost with the IP of the server, but still nothing.

Anyone an idea what i did wrong?

**Comment by lmenezes** [comment] 2015-06-01 16:06
@Yzord you will have to restart your elasticsearch instance for that to work :)
Let me know if this solves your issue.

**Comment by lmenezes** [comment] 2015-06-04 19:39
@Yzord any feedback on this?

**Comment by lmenezes** [comment] 2015-06-09 17:48
@Yzord if you still have problems with this let me know

**Comment by Yzord** [comment] 2015-06-16 07:38
I'm sorry, i was on a holiday and after that my dad died :( 

I restarted elasticsearch more then once, but i get nothing on that url. Localhost and IP are not reacting...get a 404 error all the time.

**Comment by lmenezes** [comment] 2015-06-16 07:41
when you first start elasticsearch, do you see that the plugin was correctly loaded?
```
[2015-06-15 15:11:29,975][INFO ][node                     ] [Mr. Justice] version[1.5.1], pid[30286], build[5e38401/2015-04-09T13:41:35Z]
[2015-06-15 15:11:29,976][INFO ][node                     ] [Mr. Justice] initializing ...
[2015-06-15 15:11:29,982][INFO ][plugins                  ] [Mr. Justice] loaded [], sites [kopf]
```

**Comment by Yzord** [comment] 2015-06-16 08:44
Yes, i found this in the elasticsearch.log

[2015-06-16 09:26:44,651][INFO ][node                     ] [Feral] stopping ...
[2015-06-16 09:26:45,831][INFO ][node                     ] [Feral] stopped
[2015-06-16 09:26:45,831][INFO ][node                     ] [Feral] closing ...
[2015-06-16 09:26:45,900][INFO ][node                     ] [Feral] closed
[2015-06-16 09:27:36,980][INFO ][node                     ] [Kaluu] version[1.5.1], pid[1278], build[5e38401/2015-04-09T13:41:35Z]
[2015-06-16 09:27:36,995][INFO ][node                     ] [Kaluu] initializing ...
[2015-06-16 09:27:37,067][INFO ][plugins                  ] [Kaluu] loaded [], sites [HQ, kopf]
[2015-06-16 09:27:46,469][INFO ][node                     ] [Kaluu] initialized
[2015-06-16 09:27:46,469][INFO ][node                     ] [Kaluu] starting ...
[2015-06-16 09:27:46,564][INFO ][transport                ] [Kaluu] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[localhost/127.0.0.1:9300]}
[2015-06-16 09:27:46,577][INFO ][discovery                ] [Kaluu] elasticsearch/jHsMu6TbQrmctOihvBf1Xw
[2015-06-16 09:27:49,598][INFO ][cluster.service          ] [Kaluu] new_master [Kaluu][jHsMu6TbQrmctOihvBf1Xw][havok.domain.nl][inet[localhost/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
[2015-06-16 09:27:49,719][INFO ][http                     ] [Kaluu] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[localhost/127.0.0.1:9200]}
[2015-06-16 09:27:49,722][INFO ][node                     ] [Kaluu] started
[2015-06-16 09:27:51,166][INFO ][gateway                  ] [Kaluu] recovered [60] indices into cluster_state

But no respons. I normally access Kibana4 on http://havok.domain.nl:5601 which works, but when i replace 5601 with 9200/_plugin/kopf nothing happens and results in a 404 error.

**Comment by lmenezes** [comment] 2015-06-16 08:54
and the other plugin(HQ) works?

**Comment by Yzord** [comment] 2015-06-16 09:29
Nope, that also doesn't work. But even when i go to http://havok.domain.nl:9200 i get an error it seems. http://havok.domain.nl:5601 is working. I also receive this errors:

[2015-06-16 10:38:04,542][INFO ][cluster.routing.allocation.decider] [Kaluu] high disk watermark exceeded on one or more nodes, rerouting shards
[2015-06-16 10:38:34,577][WARN ][cluster.routing.allocation.decider] [Kaluu] high disk watermark [10%] exceeded on [jHsMu6TbQrmctOihvBf1Xw][Kaluu] free: 3gb[8.6%], shards will be relocated away from this node
[2015-06-16 10:39:04,544][WARN ][cluster.routing.allocation.decider] [Kaluu] high disk watermark [10%] exceeded on [jHsMu6TbQrmctOihvBf1Xw][Kaluu] free: 3gb[8.6%], shards will be relocated away from this node
[2015-06-16 10:39:04,544][INFO ][cluster.routing.allocation.decider] [Kaluu] high disk watermark exceeded on one or more nodes, rerouting shards

**Comment by lmenezes** [comment] 2015-06-17 19:43
I'm guessing you have a reverse proxy in front of elasticsearch and something about this configuration is not quite right. but i don't have enough information to actually help you.

**Comment by rohitkothari** [comment] 2015-07-10 06:05
@Yzord 
I also faced the same issue today, got a 404 on kopf while I was able to get to kibana. But fixed it with following settings:

In my */usr/share/elasticsearch/plugins/kopf/_site/kopf_external_settings.json* file, I updated this line as follows:
``` "elasticsearch_root_path": "/es" ```

I used nginx as a reverse proxy in front of elasticsearch (suppose you are using too). Then, in my nginx config, I used the following setting:
```
server {
  listen       8080;
  server_name  localhost;

  location ~ ^/es.*$ {
    proxy_pass http://localhost:9200;
    rewrite ^/es(.*) /$1 break;
  }

  location ~ ^/kopf/.*$ {
    proxy_pass http://localhost:9200;
    rewrite ^/kopf/(.*) /_plugin/kopf/$1 break;
  }
}
```

Then I was able to access kopf by pointing my browser to ```http://server_ip:8080/kopf/```

Let me know if this helps to some extent.

**Comment by lmenezes** [comment] 2015-07-27 08:51
@Yzord is this still an issue?

**Comment by lmenezes** [comment] 2015-07-31 07:50
I will close this for now. If you still can't install kopf, please open another issue.

**Closed by lmenezes** 2015-07-31 07:50 UTC

**Comment by GlombSt** [comment] 2016-05-28 10:47
Ran into the same issue and found that I had 2 installations of elasticsearch, under /opt and /usr/share/ Init scripts were launching the "unexpected" copy that did not have the plugin.

**Comment by stephan2012** [comment] 2016-08-23 07:51
I was just facing the same symptoms but found another root cause: umask was set to 077 meaning the plugin was correctly installed but inaccessible from Elasticsearch. Removing the plugin, settings umask to 022, and finally re-installing Kopf solved my issue. Manually fixing the permissions should work, too.
