### ISSUE TITLE
Analysis view clears the "index name" when auto refresh happens

### ISSUE THREAD

**Issue by rokeller** [lmenezes/elasticsearch-kopf#242] opened 2015-03-02 09:04 UTC
**Repro Steps:**
1. In the "Analysis" view, set an index name, type and field name.
2. Wait until auto-refresh happens

**Expected Behavior:**
If the index still exists, the index remains selected.

**Observed Behavior:**
The "index name" field gets cleared when the cluster info is auto-refreshed.

**Comment by lmenezes** [comment] 2015-03-02 09:37
which version are you using? this was reported before https://github.com/lmenezes/elasticsearch-kopf/issues/216 but has been solved, and I can't reproduce the behaviour with most recent version.

**Comment by rokeller** [comment] 2015-03-02 09:39
v1.4.3 ... let me try the latest.

**Comment by lmenezes** [comment] 2015-03-09 21:02
@rokeller I will close this for now. If you still have this problem, just reopen the issue :)

**Closed by lmenezes** 2015-03-09 21:02 UTC
