### ISSUE TITLE
Add overview of recovering/initializing shards

### ISSUE THREAD

**Issue by darkoc** [lmenezes/elasticsearch-kopf#339] opened 2016-01-26 10:35 UTC
It would be very useful to have a panel where one can see all of the shards which are currently recovering, which stage of recovery are they in, to what percentage is the file transfer completed, which node are they being copied from, and so on.
At the moment, I find myself constantly clicking 'show shard stats' to get this information for shards which are being recovered.

**Comment by up-town-down** [comment] 2016-01-26 19:48
Duplicate of #297 ?

**Comment by darkoc** [comment] 2016-02-04 20:13
Yes, feel free to close this one in favor of #297

**Comment by lmenezes** [comment] 2016-10-08 04:02
@up-town-down thanks for this one as well :)

**Closed** 2016-10-08 04:01 UTC
